[versions]
# dependencies
androidx-activityCompose = "1.8.2"
androidx-appcompat = "1.6.1"
androidx-composeBom = "2024.02.01"
androidx-compose-material3 = "1.2.0"
androidx-compose-ui = "1.6.2"
androidx-coreKtx = "1.12.0"
androidx-hiltNavigationCompose = "1.2.0"
androidx-lifecycleRuntimeKtx = "2.7.0"
androidx-room = "2.6.1"
coil-compose = "2.6.0"
google-material = "1.11.0"
hild-android = "2.51"
hilt-android-compiler = "2.51"
navigation-lifecycleRuntimeCompose = "2.7.0"
logging-interceptor = "4.12.0"
moshiKotlin = "1.15.1"
moshiKotlinCodegen = "1.15.1"
navigation-compose = "2.7.7"
retrofit2 = "2.9.0"

# plugins
androidGradlePlugin = "8.3.0"
androidLibraryPlugin = "8.3.0"
hiltPlugin = "2.51"
kotlinPlugin = "1.9.22"
kotlinSymbomProcessing = "1.9.22-1.0.17"

[libraries]
androidx-activity-activityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activityCompose" }
androidx-compose-composeBom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-composeBom" }
androidx-compose-material3-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidx-compose-material3" }
androidx-compose-ui-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "androidx-compose-ui" }
androidx-compose-ui-uiGraphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "androidx-compose-ui" }
androidx-compose-ui-uiTooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "androidx-compose-ui" }
androidx-compose-ui-uiTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "androidx-compose-ui" }
androidx-compose-ui-uiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "androidx-compose-ui" }
androidx-core-coreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-coreKtx" }
androidx-hilt-hiltNavigationCompose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidx-hiltNavigationCompose" }
androidx-lifecycle-lifecycleRuntimeKtx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycleRuntimeKtx" }
androidx-lifecycle-lifecycleRuntimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "navigation-lifecycleRuntimeCompose" }
androidx-navigation-navigationCompose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
androidx-room-roomCompiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }
androidx-room-roomKtx = { group = "androidx.room", name = "room-ktx", version.ref = "androidx-room" }
androidx-room-roomRuntime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }
google-dagger-hiltAndroid = { group = "com.google.dagger", name = "hilt-android", version.ref = "hild-android" }
google-dagger-hiltAndroidCompiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt-android-compiler" }
coilKt-coilCompose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil-compose" }
moshi-moshiKotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshiKotlin" }
moshi-moshiKotlinCodegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshiKotlinCodegen" }
refrofit2-converterMoshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit2" }
refrofit2-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit2" }
okhttp3-loggingInterceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "logging-interceptor" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidLibraryPlugin" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltPlugin" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlinSymbomProcessing" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinPlugin" }
kotlin-kapt = { id = "kotlin-kapt", version = "" }

[bundles]